### ISSUE TITLE
Software closes when plotting

### ISSUE THREAD

**Issue by soluna1** [planktontoolbox/plankton-toolbox#19]
Hi, me again, I'm testing and customising the software to start working, but it closes when I try to see the plots. It seems something with libraries and configuration. This is the error report in terminal Mac before collapsing:

libpng warning: iCCP: known incorrect sRGB profile
prueba
objc[2499]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fffa6d1ca70) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x120e92cd8). One of the two will be used. Which one is undefined.
Traceback (most recent call last):
  File "matplotlib/backends/backend_qt4.py", line 36, in wheelEvent
AttributeError: 'QWheelEvent' object has no attribute 'delta'
Abort trap: 6

Any suggestion?

Thanks a lot.

**Comment by soluna1** [comment]
Hi,
Just to comment that the issue I reported before keeps happening in the Dataset Analysis section, particularly with plots. The problem is that the tool crashes and it is necessary to upload the dataset again. I copy the log at terminal Mac in case it could help.

Thanks

objc[63658]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fffae38da70) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x1205efcd8). One of the two will be used. Which one is undefined.
Traceback (most recent call last):
  File "matplotlib/backends/backend_qt4.py", line 36, in wheelEvent
AttributeError: 'QWheelEvent' object has no attribute 'delta'
Abort trap: 6
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by arnoldandreasson** [comment]
Thanks.

Last week I created a test version for the next release of PTBX. The Windows version seems to be ok but there was no time to dig into the Mac problems. I hope to test it this week and then give you a link to the next test version for Mac.  
Maybe "matplotlib/backends/backend_qt4.py" is a part of the problem since I use qt5. 

And I have started to use the Issue tracker myself, inspired by your first issue :)

   / Arnold

**Comment by soluna1** [comment]
That's great, tell when I can test it. I've been using the tool from 3 weeks now, and it is really comfortable for counting. Now, I'm preparing some previous data to be loaded and it seems to work fine. I've some ideas to improve it, but let's see the new version first. Really happy with this option. Thanks a lot!

**Comment by arnoldandreasson** [comment]
Check if you can use this one: https://drive.google.com/file/d/1sNnL14U549Ao6ThYxK5qWIV6isAAIYy_/view?usp=sharing <https://drive.google.com/file/d/1sNnL14U549Ao6ThYxK5qWIV6isAAIYy_/view?usp=sharing> 

I put it in a zip file because we had problems when uploading the file directly.

What species lists do you use? It should also be nice if you can send over an example of a counted sample. The Excel export is probably the best option.

And please add suggested improvements to the issue tracker or email me.

    / Arnold

**Comment by soluna1** [comment]
Ohh great!! I've downloaded the file, and I'll try it tomorrow. At the moment, I'm using mostly Helcom  list, I've added one or two, but nothing extraordinary. Yes, of course I can send some counts in excel file, and also a couple of things to improve the interface for counting, which I think could be useful and not too difficult to implement. Thanks again for your feedback.

**Comment by arnoldandreasson** [comment]
No problems in the new release. (May be connected to the switch from Qt4 to Qt5 and a referens to qt4 for plotting).
